-- SELECT_QUERY_START
SELECT 
    PROJECT_ID, PROJECT_NAME, DEPARTMENT, START_DATE, END_DATE, BUDGET
FROM {{ database }}.{{ schema }}.{{ table }}
WHERE START_DATE >= '2024-01-01'
ORDER BY START_DATE;
-- SELECT_QUERY_END

-- MERGE_QUERY_START
MERGE INTO {{ database }}.{{ schema }}.{{ table }} AS target
USING (
    SELECT 1 AS EMP_ID, '2024-07-01'::DATE AS ATTENDANCE_DATE, 'Present' AS STATUS
    UNION ALL
    SELECT 2, '2024-07-01'::DATE, 'Leave'
    UNION ALL
    SELECT 3, '2024-07-01'::DATE, 'Absent'
) AS source
ON target.EMP_ID = source.EMP_ID AND target.ATTENDANCE_DATE = source.ATTENDANCE_DATE
WHEN MATCHED THEN
    UPDATE SET target.STATUS = source.STATUS
WHEN NOT MATCHED THEN
    INSERT (EMP_ID, ATTENDANCE_DATE, STATUS)
    VALUES (source.EMP_ID, source.ATTENDANCE_DATE, source.STATUS);
-- MERGE_QUERY_END

-- AGGREGATE_QUERY_START
SELECT 
    DEPARTMENT,
    COUNT(*) AS TOTAL_EMPLOYEES,
    ROUND(AVG(SALARY), 2) AS AVG_SALARY,
    ROUND(MAX(SALARY), 2) AS MAX_SALARY,
    ROUND(MIN(SALARY), 2) AS MIN_SALARY
FROM {{ database }}.{{ schema }}.{{ table }}
GROUP BY DEPARTMENT
ORDER BY TOTAL_EMPLOYEES DESC;
-- AGGREGATE_QUERY_END
