
-- Create database CUSTOMER_DB;
-- Create schema WEATHER_SCHEMA;

-- Step 1: Create a role
CREATE ROLE USER_ROLE;

-- Step 2: Grant required access to the role
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE USER_ROLE;
GRANT USAGE ON DATABASE CUSTOMER_DB TO ROLE USER_ROLE;
GRANT USAGE ON SCHEMA CUSTOMER_DB.WEATHER_SCHEMA TO ROLE USER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA CUSTOMER_DB.WEATHER_SCHEMA TO ROLE USER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CUSTOMER_DB.WEATHER_SCHEMA TO ROLE USER_ROLE;

-- Step 3: Create 3 users and assign the role
-- User 1
CREATE USER WEATHER_USER1
  PASSWORD = 'Temp@1234'
  DEFAULT_ROLE = USER_ROLE
  DEFAULT_WAREHOUSE = COMPUTE_WH
  DEFAULT_NAMESPACE = CUSTOMER_DB.WEATHER_SCHEMA
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE USER_ROLE TO USER WEATHER_USER1;

-- User 2
CREATE USER WEATHER_USER2
  PASSWORD = 'Temp@1234'
  DEFAULT_ROLE = USER_ROLE
  DEFAULT_WAREHOUSE = COMPUTE_WH
  DEFAULT_NAMESPACE = CUSTOMER_DB.WEATHER_SCHEMA
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE USER_ROLE TO USER WEATHER_USER2;

-- User 3
CREATE USER WEATHER_USER3
  PASSWORD = 'Temp@1234'
  DEFAULT_ROLE = USER_ROLE
  DEFAULT_WAREHOUSE = COMPUTE_WH
  DEFAULT_NAMESPACE = CUSTOMER_DB.WEATHER_SCHEMA
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE USER_ROLE TO USER WEATHER_USER3;


-- Drop user WEATHER_USER1;
-- Drop user WEATHER_USER2;
-- Drop user WEATHER_USER3;
