create database airflow_practice;

SELECT CURRENT_ACCOUNT();


CREATE ROLE IF NOT EXISTS DEV_ROLE;

CREATE ROLE IF NOT EXISTS PROD_ROLE;



-- Create DEV_USER
CREATE USER IF NOT EXISTS DEV_USER
  PASSWORD = 'DevUser@123'
  DEFAULT_ROLE = DEV_ROLE
  DEFAULT_WAREHOUSE = DEV_WH
  DEFAULT_NAMESPACE = DEV_DB.DEV_SCHEMA;

GRANT ROLE DEV_ROLE TO USER DEV_USER;

-- Create PROD_USER
CREATE USER IF NOT EXISTS PROD_USER
  PASSWORD = 'ProdUser@123'
  DEFAULT_ROLE = PROD_ROLE
  DEFAULT_WAREHOUSE = PROD_WH
  DEFAULT_NAMESPACE = PROD_DB.PROD_SCHEMA;

GRANT ROLE PROD_ROLE TO USER PROD_USER;

CREATE WAREHOUSE IF NOT EXISTS DEV_WH
WITH WAREHOUSE_SIZE = XSMALL
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS PROD_WH
WITH WAREHOUSE_SIZE = XSMALL
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS DEV_DB;
CREATE DATABASE IF NOT EXISTS PROD_DB;

CREATE SCHEMA IF NOT EXISTS DEV_DB.DEV_SCHEMA;
CREATE SCHEMA IF NOT EXISTS PROD_DB.PROD_SCHEMA;

-- Step 1: Grant USAGE on the database (if needed)
GRANT USAGE ON DATABASE DEV_DB TO ROLE DEV_ROLE;

-- Step 2: Grant USAGE on the schema
GRANT USAGE ON SCHEMA DEV_DB.DEV_SCHEMA TO ROLE DEV_ROLE;

-- Step 3: Grant CREATE TABLE and INSERT privileges
GRANT CREATE TABLE, INSERT, SELECT ON SCHEMA DEV_DB.DEV_SCHEMA TO ROLE DEV_ROLE;


-- Grant warehouse access
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE DEV_ROLE;

-- Grant database & schema usage
GRANT USAGE ON DATABASE DEV_DB TO ROLE DEV_ROLE;
GRANT USAGE ON SCHEMA DEV_DB.DEV_SCHEMA TO ROLE DEV_ROLE;

-- Grant access to all tables in schema
GRANT ALL PRIVILEGES ON SCHEMA DEV_DB.DEV_SCHEMA TO ROLE DEV_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA PROD_DB.PROD_SCHEMA TO ROLE PROD_ROLE;


GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DEV_DB.DEV_SCHEMA TO ROLE DEV_ROLE;

-- Future table access
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DEV_DB.DEV_SCHEMA TO ROLE DEV_ROLE;

-- 
GRANT USAGE ON WAREHOUSE PROD_WH TO ROLE PROD_ROLE;
GRANT USAGE ON DATABASE PROD_DB TO ROLE PROD_ROLE;
GRANT USAGE ON SCHEMA PROD_DB.PROD_SCHEMA TO ROLE PROD_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PROD_DB.PROD_SCHEMA TO ROLE PROD_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PROD_DB.PROD_SCHEMA TO ROLE PROD_ROLE;


