x-airflow-common:
  &airflow-common
  image: apache/airflow:2.8.1
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-snowflake"
    AIRFLOW_ENV: dev
    AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
    AIRFLOW__SMTP__SMTP_HOST: smtp.outlook.com
    AIRFLOW__SMTP__SMTP_STARTTLS: 'True'
    AIRFLOW__SMTP__SMTP_SSL: 'False'
    AIRFLOW__SMTP__SMTP_PORT: 587
    AIRFLOW__SMTP__SMTP_MAIL_FROM: manan.gupta@growexx.com
    AIRFLOW__SMTP__SMTP_USER: manan.gupta@growexx.com
    AIRFLOW__SMTP__SMTP_PASSWORD: Manan.growexx@2001
    
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./config/dev:/opt/airflow/dev
    - ./config/prod:/opt/airflow/prod
    - ./scripts:/opt/airflow/scripts
    - ./config:/opt/airflow/config 
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username admin --password admin --firstname Manan --lastname Gupta --role Admin --email admin@example.com && python /opt/airflow/scripts/load_connections.py && pip install -r /requirements.txt"
    volumes:
      - ./scripts:/opt/airflow/scripts
      - ./config/dev:/opt/airflow/dev
      - ./config:/opt/airflow/config


  webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    <<: *airflow-common
    command: scheduler

volumes:
  postgres-db-volume:
